// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: EVCC-Display

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_mainCont;
lv_obj_t * ui_homeCont;
lv_obj_t * ui_homeBarCont;
lv_obj_t * ui_PanelSolar;
lv_obj_t * ui_LabelSolar;
lv_obj_t * ui_PanelUsing;
lv_obj_t * ui_LabelUsing;
lv_obj_t * ui_imgSolar;
lv_obj_t * ui_imgGrid;
lv_obj_t * ui_carCont;
lv_obj_t * ui_carBarCont;
lv_obj_t * ui_PanelSoc;
lv_obj_t * ui_LabelSoc;
lv_obj_t * ui_PanelMax;
lv_obj_t * ui_battery;
lv_obj_t * ui_infoCont;
lv_obj_t * ui_chargeLbl;
lv_obj_t * ui_imgCar;
lv_obj_t * ui_showerg;
lv_obj_t * ui_showerw;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_batery[2] = {&ui_img_batery40_png, &ui_img_batery24_png};
const lv_img_dsc_t * ui_imgset_solar[1] = {&ui_img_solar24_png};
const lv_img_dsc_t * ui_imgset_auto[1] = {&ui_img_auto24_png};
const lv_img_dsc_t * ui_imgset_power[1] = {&ui_img_power24_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
}
