// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: EVCC-Display

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainCont = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_mainCont);
    lv_obj_set_width(ui_mainCont, lv_pct(100));
    lv_obj_set_height(ui_mainCont, lv_pct(100));
    lv_obj_set_align(ui_mainCont, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_mainCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_homeCont = lv_obj_create(ui_mainCont);
    lv_obj_remove_style_all(ui_homeCont);
    lv_obj_set_width(ui_homeCont, lv_pct(100));
    lv_obj_set_height(ui_homeCont, lv_pct(30));
    lv_obj_set_align(ui_homeCont, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_homeCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_homeBarCont = lv_obj_create(ui_homeCont);
    lv_obj_remove_style_all(ui_homeBarCont);
    lv_obj_set_width(ui_homeBarCont, lv_pct(90));
    lv_obj_set_height(ui_homeBarCont, lv_pct(40));
    lv_obj_set_align(ui_homeBarCont, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_homeBarCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_PanelSolar = lv_obj_create(ui_homeBarCont);
    lv_obj_set_width(ui_PanelSolar, lv_pct(20));
    lv_obj_set_height(ui_PanelSolar, lv_pct(100));
    lv_obj_set_align(ui_PanelSolar, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_PanelSolar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_PanelSolar, lv_color_hex(0x07E179), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSolar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSolar = lv_label_create(ui_PanelSolar);
    lv_obj_set_width(ui_LabelSolar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSolar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSolar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSolar, "234");
    lv_obj_remove_flag(ui_LabelSolar, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelSolar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSolar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSolar, &ui_font_ubuntu16b, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelUsing = lv_obj_create(ui_homeBarCont);
    lv_obj_set_width(ui_PanelUsing, lv_pct(80));
    lv_obj_set_height(ui_PanelUsing, lv_pct(100));
    lv_obj_set_align(ui_PanelUsing, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_PanelUsing, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_PanelUsing, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelUsing, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUsing = lv_label_create(ui_PanelUsing);
    lv_obj_set_width(ui_LabelUsing, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUsing, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelUsing, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUsing, "1234");
    lv_obj_remove_flag(ui_LabelUsing, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelUsing, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUsing, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUsing, &ui_font_ubuntu16b, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgSolar = lv_image_create(ui_homeCont);
    lv_image_set_src(ui_imgSolar, &ui_img_solar24_png);
    lv_obj_set_width(ui_imgSolar, LV_SIZE_CONTENT);   /// 34
    lv_obj_set_height(ui_imgSolar, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_y(ui_imgSolar, 0);
    lv_obj_set_x(ui_imgSolar, lv_pct(5));
    lv_obj_set_align(ui_imgSolar, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_imgSolar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_imgSolar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgGrid = lv_image_create(ui_homeCont);
    lv_image_set_src(ui_imgGrid, &ui_img_power24_png);
    lv_obj_set_width(ui_imgGrid, LV_SIZE_CONTENT);   /// 23
    lv_obj_set_height(ui_imgGrid, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_y(ui_imgGrid, 0);
    lv_obj_set_x(ui_imgGrid, lv_pct(-5));
    lv_obj_set_align(ui_imgGrid, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_imgGrid, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_imgGrid, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_carCont = lv_obj_create(ui_mainCont);
    lv_obj_remove_style_all(ui_carCont);
    lv_obj_set_width(ui_carCont, lv_pct(100));
    lv_obj_set_height(ui_carCont, lv_pct(30));
    lv_obj_set_x(ui_carCont, 0);
    lv_obj_set_y(ui_carCont, lv_pct(30));
    lv_obj_set_align(ui_carCont, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_carCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_carBarCont = lv_obj_create(ui_carCont);
    lv_obj_remove_style_all(ui_carBarCont);
    lv_obj_set_width(ui_carBarCont, lv_pct(90));
    lv_obj_set_height(ui_carBarCont, lv_pct(40));
    lv_obj_set_align(ui_carBarCont, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_carBarCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_PanelSoc = lv_obj_create(ui_carBarCont);
    lv_obj_set_width(ui_PanelSoc, lv_pct(20));
    lv_obj_set_height(ui_PanelSoc, lv_pct(100));
    lv_obj_set_align(ui_PanelSoc, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_PanelSoc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_PanelSoc, lv_color_hex(0x07E179), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSoc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSoc = lv_label_create(ui_PanelSoc);
    lv_obj_set_width(ui_LabelSoc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSoc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSoc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSoc, "20 %");
    lv_obj_remove_flag(ui_LabelSoc, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelSoc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSoc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSoc, &ui_font_ubuntu16b, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelMax = lv_obj_create(ui_carBarCont);
    lv_obj_set_width(ui_PanelMax, lv_pct(80));
    lv_obj_set_height(ui_PanelMax, lv_pct(100));
    lv_obj_set_align(ui_PanelMax, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_PanelMax, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_PanelMax, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelMax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_battery = lv_image_create(ui_carCont);
    lv_image_set_src(ui_battery, &ui_img_batery24_png);
    lv_obj_set_width(ui_battery, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_battery, LV_SIZE_CONTENT);    /// 13
    lv_obj_set_y(ui_battery, 0);
    lv_obj_set_x(ui_battery, lv_pct(5));
    lv_obj_set_align(ui_battery, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_battery, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_battery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infoCont = lv_obj_create(ui_mainCont);
    lv_obj_remove_style_all(ui_infoCont);
    lv_obj_set_width(ui_infoCont, lv_pct(100));
    lv_obj_set_height(ui_infoCont, lv_pct(30));
    lv_obj_set_align(ui_infoCont, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_infoCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chargeLbl = lv_label_create(ui_infoCont);
    lv_obj_set_width(ui_chargeLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chargeLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_chargeLbl, 0);
    lv_obj_set_x(ui_chargeLbl, lv_pct(25));
    lv_label_set_text(ui_chargeLbl, "0,0 kW");
    lv_obj_set_style_text_color(ui_chargeLbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chargeLbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_chargeLbl, &ui_font_ubuntu30b, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgCar = lv_image_create(ui_infoCont);
    lv_image_set_src(ui_imgCar, &ui_img_auto24_png);
    lv_obj_set_width(ui_imgCar, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_imgCar, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_y(ui_imgCar, 0);
    lv_obj_set_x(ui_imgCar, lv_pct(5));
    lv_obj_add_flag(ui_imgCar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_imgCar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgHouse = lv_image_create(ui_infoCont);
    lv_image_set_src(ui_imgHouse, &ui_img_house24_png);
    lv_obj_set_width(ui_imgHouse, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_imgHouse, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_y(ui_imgHouse, 0);
    lv_obj_set_x(ui_imgHouse, lv_pct(-5));
    lv_obj_set_align(ui_imgHouse, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_imgHouse, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_imgHouse, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chargeLbl1 = lv_label_create(ui_infoCont);
    lv_obj_set_width(ui_chargeLbl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chargeLbl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_chargeLbl1, 0);
    lv_obj_set_x(ui_chargeLbl1, lv_pct(-15));
    lv_obj_set_align(ui_chargeLbl1, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_chargeLbl1, "0,0 %");
    lv_obj_set_style_text_color(ui_chargeLbl1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chargeLbl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_chargeLbl1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_chargeLbl1, &ui_font_ubuntu30b, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_showerg = lv_image_create(ui_MainScreen);
    lv_image_set_src(ui_showerg, &ui_img_1743798666);
    lv_obj_set_width(ui_showerg, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_showerg, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_align(ui_showerg, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_showerg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_showerg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_showerw = lv_image_create(ui_MainScreen);
    lv_image_set_src(ui_showerw, &ui_img_1743782298);
    lv_obj_set_width(ui_showerw, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_showerw, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_align(ui_showerw, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_showerw, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_showerw, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
